CREATE DATABASE QLBD
ON(name = 'QLBD_DATA', filename = 'D:\Data\TH3 SQL\QLBD.MDF')
LOG ON (name = 'QLBD_LOG', filename = 'D:\Data\TH3 SQL\QLBD.LDF')

USE QLBD

CREATE TABLE DOI(
	MADOI CHAR(3) NOT NULL PRIMARY KEY,
	TENDOI NVARCHAR(50),
);

CREATE TABLE TRANDAU(
	MATD CHAR(2) NOT NULL PRIMARY KEY,
	MASAN CHAR(3) NOT NULL,
	NGAY DATE,
	GIO TIME
);

CREATE TABLE CT_TRANDAU(
	MATD CHAR(2) NOT NULL,
	MADOI CHAR(3) NOT NULL,
	SOBANTHANG TINYINT,
	PRIMARY KEY(MATD, MADOI),
	CONSTRAINT chk_SOBANTHANG CHECK (SOBANTHANG >= 0)
);

ALTER TABLE CT_TRANDAU
ADD CONSTRAINT FK_CT_TRANDAU_TRANDAU FOREIGN KEY(MATD) REFERENCES TRANDAU(MATD)

ALTER TABLE CT_TRANDAU
ADD CONSTRAINT FK_CT_TRANDAU_DOI FOREIGN KEY(MADOI) REFERENCES DOI(MADOI)