-- Cau 1:
-- a)
SELECT *
FROM [dbo].[TINH_TP]
Where DT >= 5000;
-- b)
SELECT *
FROM [dbo].[TINH_TP]
Where DT >= 6000;
-- Cau 2, 3, 4:
SELECT *
FROM [dbo].[TINH_TP]
WHERE MIEN = 'Bac';
-- Cau 5:
SELECT T.TEN_TTP
FROM TINH_TP AS T
JOIN BIENGIOI AS B ON T.MA_TTP = B.MA_TTP
WHERE T.MIEN = 'Bac';
-- Cau 6:
SELECT (SUM([DT]) / COUNT([MA_TTP])) AS [Tong Dien Tich]
FROM [dbo].[TINH_TP];
-- Cau 7:
SELECT [DS], [TEN_TTP] 
FROM [dbo].[TINH_TP]
WHERE [DT] > 7000
-- Cau 8:
SELECT [DS], [TEN_TTP]
FROM [dbo].[TINH_TP]
WHERE MIEN = 'Bac';
-- Cau 9:
SELECT DISTINCT B.NUOC
FROM [dbo].[BIENGIOI] AS B
JOIN  TINH_TP AS T ON T.MA_TTP = B.MA_TTP
WHERE T.MIEN = 'Nam';
-- Cau 10:
SELECT AVG([DT]) AS [Tong Dien Tich]
FROM [dbo].[TINH_TP];
-- Cau 11:
SELECT [TEN_TTP], ([DS] / [DT]) AS [Mat Do Dan So]
FROM [dbo].[TINH_TP];
-- Cau 12:	
SELECT T2.TEN_TTP
FROM [dbo].[LANGGIENG] AS L
JOIN [dbo].[TINH_TP] AS T1 ON T1.MA_TTP = L.MA_TTP
JOIN [dbo].[TINH_TP] AS T2 ON T2.MA_TTP = L.LG
WHERE T1.TEN_TTP = 'Long An';
-- Cau 13:
SELECT COUNT([MA_TTP]) AS [Giap CPC]
FROM [dbo].[BIENGIOI]
WHERE NUOC = 'CPC';
-- Cau 14:
SELECT TOP 1 [TEN_TTP], [DT]
FROM [dbo].[TINH_TP]
ORDER BY [DT] DESC
-- Cau 15:
SELECT TOP 1 [TEN_TTP], (DS / DT) AS [Mat Do Dan So]
FROM [dbo].[TINH_TP]
ORDER BY [Mat Do Dan So] DESC;
-- Cau 16:
SELECT T.TEN_TTP
FROM [dbo].[BIENGIOI] AS B
JOIN [dbo].[TINH_TP] AS T ON T.MA_TTP = B.MA_TTP
GROUP BY T.TEN_TTP
HAVING COUNT(B.NUOC) >= 2
-- Cau 17:
SELECT [MIEN], [TEN_TTP]
FROM [dbo].[TINH_TP]
ORDER BY [MIEN], [TEN_TTP];
-- Cau 18:
SELECT T.TEN_TTP, COUNT(L.LG) AS SoLuongLangGieng
FROM [dbo].[LANGGIENG] AS L
JOIN [dbo].[TINH_TP] AS T ON T.MA_TTP = L.MA_TTP
GROUP BY T.TEN_TTP
HAVING COUNT(L.LG) = (
    SELECT MAX(SoLuong) 
    FROM (
        SELECT COUNT(L.LG) AS SoLuong
        FROM [dbo].[LANGGIENG] AS L
        GROUP BY L.MA_TTP
    ) AS SubQuery
);
-- Cau 19:
SELECT TEN_TTP
FROM TINH_TP
WHERE DT < (SELECT AVG(DT) FROM TINH_TP);
-- Cau 20:
SELECT DISTINCT T2.TEN_TTP
FROM LANGGIENG L
JOIN TINH_TP T1 ON L.MA_TTP = T1.MA_TTP
JOIN TINH_TP T2 ON L.LG = T2.MA_TTP
WHERE T1.MIEN = 'Nam' AND T2.MIEN != 'Nam';
-- Cau 21:
SELECT T1.TEN_TTP, T1.DT
FROM TINH_TP T1
WHERE T1.DT > ALL (
    SELECT T2.DT 
    FROM LANGGIENG L
	JOIN TINH_TP T2 ON L.LG = T2.MA_TTP
    WHERE L.MA_TTP = T1.MA_TTP
);

