-- Cau 1:
INSERT INTO SINHVIEN ([MSSV], [HOTEN], [NTNS], [PHAI], [MALOP]) 
VALUES ('190001', 'Dao Thi Tuyet Hoa', CONVERT(DATE, '08/03/2001', 103), 0, '19DTH02');
-- Cau 2:
UPDATE [dbo].[MONHOC]
SET [TENMH] = 'Toan roi rac'
WHERE [TENMH] = 'Ly thuyet do thi'
-- Cau 3:
SELECT [TENMH]
FROM [dbo].[MONHOC]
WHERE [TCTH] = 0;
-- Cau 4:
SELECT [TENMH]
FROM [dbo].[MONHOC]
WHERE [TCTH] > 0 AND [TCLT] > 0;
-- Cau 5:
SELECT [TENMH]
FROM [dbo].[MONHOC]
WHERE [TENMH] LIKE 'C%';
-- Cau 6:
SELECT *
FROM [dbo].[SINHVIEN]
WHERE [HOTEN] LIKE '%Thi%'
-- Cau 7:
SELECT TOP 2 *
FROM [dbo].[LOP]
ORDER BY [SISO] DESC
-- Cau 8:
SELECT L.MALOP, S.MSSV, S.HOTEN, S.NTNS, S.PHAI
FROM [dbo].[SINHVIEN] AS S
JOIN LOP AS L ON L.MALOP = S.MALOP
-- Cau 9:
SELECT *
FROM [dbo].[SINHVIEN]
WHERE DATEDIFF(YEAR, [NTNS], GETDATE()) >= 20;
-- Cau 10:
SELECT M.TENMH
FROM [dbo].[MONHOC] AS M
JOIN [dbo].[DIEMSV] AS D ON M.MAMH = D.MAMH
WHERE D.DIEM IS NULL
-- Cau 11:
SELECT TOP 1 S.MSSV, S.HOTEN, M.TENMH, D.DIEM
FROM [dbo].[SINHVIEN] AS S
JOIN [dbo].[DIEMSV] AS D ON D.MSSV = S.MSSV
JOIN [dbo].[MONHOC] AS M ON M.MAMH = D.MAMH
WHERE S.MSSV = '170001';
-- Cau 12:
SELECT S.HOTEN, D.MAMH
FROM [dbo].[SINHVIEN] AS S
JOIN [dbo].[DIEMSV] AS D ON D.MSSV = S.MSSV
WHERE D.DIEM > 7
-- Cau 13:
SELECT M.TENMH, COUNT(S.MSSV) AS SoLuongSinhVien
FROM [dbo].[SINHVIEN] AS S
JOIN [dbo].[DIEMSV] AS D ON D.MSSV = S.MSSV
JOIN [dbo].[MONHOC] AS M ON M.MAMH = D.MAMH
WHERE D.DIEM IS NOT NULL
GROUP BY M.TENMH
-- Cau 14:
SELECT S.HOTEN, AVG(D.DIEM) AS DiemTrungBinh
FROM [dbo].[SINHVIEN] AS S
JOIN [dbo].[DIEMSV] AS D ON D.MSSV = S.MSSV
GROUP BY S.HOTEN
-- Cau 15:
SELECT S.HOTEN
FROM [dbo].[SINHVIEN] AS S
JOIN [dbo].[DIEMSV] AS D ON D.MSSV = S.MSSV
JOIN [dbo].[MONHOC] AS M ON M.MAMH = D.MAMH
WHERE M.TENMH = 'Ky thuat lap trinh'
AND D.DIEM = (
	SELECT MAX(DIEM)
	FROM [dbo].[DIEMSV]
	WHERE MAMH = (
		SELECT [MAMH]
		FROM [dbo].[MONHOC]
		WHERE TENMH = 'Ky thuat lap trinh'
	)
);

