CREATE DATABASE QLSV
ON(name = 'QLSV_DATA', filename = 'D:\Data\TH2 SQL\QLSV.MDF')
LOG ON(name = 'QLSV_LOG', filename = 'D:\Data\TH2 SQL\QLSV.LDF')

USE QLSV

CREATE TABLE LOP(
	MALOP CHAR(7) NOT NULL PRIMARY KEY,
	TENLOP NVARCHAR(50),
	SISO TINYINT,
	CONSTRAINT chk_SISO CHECK (SISO > 0)
);

CREATE TABLE MONHOC(
	MAMH CHAR(6) NOT NULL PRIMARY KEY,
	TENMH NVARCHAR(50),
	TCLT TINYINT,
	TCTH TINYINT,
	CONSTRAINT chk_TCLT CHECK (TCLT > 0),
	CONSTRAINT chk_TCTH CHECK (TCTH >= 0)
);

CREATE TABLE SINHVIEN(
	MSSV CHAR(6) NOT NULL PRIMARY KEY,
	HOTEN NVARCHAR(50),
	NTNS DATE,
	PHAI BIT DEFAULT 1 CHECK (PHAI IN (0,1)),
	MALOP CHAR(7),
);

ALTER TABLE SINHVIEN
ADD CONSTRAINT FK_SINHVIEN_LOP FOREIGN KEY(MALOP) REFERENCES LOP(MALOP)

CREATE TABLE DIEMSV(
	MSSV CHAR(6) NOT NULL,
	MAMH CHAR(6) NOT NULL,
	DIEM DECIMAL(3,1) CHECK (DIEM IS NULL OR (DIEM >= 0 AND DIEM <= 10)) ,
	PRIMARY KEY(MSSV, MAMH)
);

ALTER TABLE DIEMSV
ADD CONSTRAINT FK_DIEMSV_SINHVIEN FOREIGN KEY(MSSV) REFERENCES SINHVIEN(MSSV)

ALTER TABLE DIEMSV
ADD CONSTRAINT FK_DIEMSV_MONHOC FOREIGN KEY(MAMH) REFERENCES MONHOC(MAMH)


